spring:
  config:
    import: optional:file:.env[.properties]
  liquibase:
    change-log: db/changelog/db-changelog-master.xml
    drop-first: true
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
  security:
    user:
      name: ${SPRING_USERNAME}
      password: ${SPRING_PASSWORD}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/forum
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

jwt:
  auth:
    converter:
      resource-id: client
      principle-attribute: preferred_username

management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true

minio:
  url: ${MINIO_SERVER_URL}
  access-key: ${MINIO_USERNAME}
  secret-key: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}