global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: "spring"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: "prometheus"
    static_configs:
      - targets: [ "localhost:9090" ]